version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
